CREATE DATABASE IF NOT EXISTS MyDatabase DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE MyDatabase;

CREATE TABLE IF NOT EXISTS users (
    userID INT(11) AUTO_INCREMENT PRIMARY KEY,
    salt VARCHAR(255) NOT NULL,
    userName VARCHAR(255) NOT NULL,
    userPassword VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS activities (
    activityID INT(11) AUTO_INCREMENT PRIMARY KEY,
    activitiesTime DATETIME NOT NULL,
    activityName VARCHAR(255) NOT NULL,
    userID INT(11),
    FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
